#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Native.Droid.Resource", IsApplication=true)]

namespace Xamarin.Native.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int AddressField = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int DownloadedImage = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int PositionLabel = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int StartButton = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int TimeLabel = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int digitsEntry = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int fileAccessButton = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int locationButton = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int networkButton = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int performanceButton = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int readButton = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int resultView = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int startButton = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int timeLabel = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int writeButton = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FileAccessTest = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LocationTest = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NetworkTest = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PerformanceTest = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000e
			public const int addressHint = 2130968590;
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int descFileAccess = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int descLocation = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int descNetwork = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int descPerformance = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int digitsHint = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int menu = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int menuFileAccess = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int menuLocation = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int menuNetwork = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int menuPerformance = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int readButton = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int startButton = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int writeButton = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
